In [13]:
import sys
if sys.version_info[0] < 3:
    raise Exception("Python 3 not detected")
    
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.feature_extraction import DictVectorizer

In [14]:
df = pd.read_csv("C:/Users/Eden/Desktop/personal_projects/widsdatathon2021/TrainingWiDS2021.csv")

In [15]:
dic = pd.read_csv("C:/Users/Eden/Desktop/personal_projects/widsdatathon2021/DataDictionaryWiDS2021.csv")

In [33]:
labs_name = dic.loc[dic["Category"].isin(["labs", "labs blood gas"])]["Variable Name"].tolist()
labs_name

['d1_albumin_max',
 'd1_albumin_min',
 'd1_bilirubin_max',
 'd1_bilirubin_min',
 'd1_bun_max',
 'd1_bun_min',
 'd1_calcium_max',
 'd1_calcium_min',
 'd1_creatinine_max',
 'd1_creatinine_min',
 'd1_glucose_max',
 'd1_glucose_min',
 'd1_hco3_max',
 'd1_hco3_min',
 'd1_hemaglobin_max',
 'd1_hemaglobin_min',
 'd1_hematocrit_max',
 'd1_hematocrit_min',
 'd1_inr_max',
 'd1_inr_min',
 'd1_lactate_max',
 'd1_lactate_min',
 'd1_platelets_max',
 'd1_platelets_min',
 'd1_potassium_max',
 'd1_potassium_min',
 'd1_sodium_max',
 'd1_sodium_min',
 'd1_wbc_max',
 'd1_wbc_min',
 'h1_albumin_max',
 'h1_albumin_min',
 'h1_bilirubin_max',
 'h1_bilirubin_min',
 'h1_bun_max',
 'h1_bun_min',
 'h1_calcium_max',
 'h1_calcium_min',
 'h1_creatinine_max',
 'h1_creatinine_min',
 'h1_glucose_max',
 'h1_glucose_min',
 'h1_hco3_max',
 'h1_hco3_min',
 'h1_hemaglobin_max',
 'h1_hemaglobin_min',
 'h1_hematocrit_max',
 'h1_hematocrit_min',
 'h1_inr_max',
 'h1_inr_min',
 'h1_lactate_max',
 'h1_lactate_min',
 'h1_platelets_max',
 'h1_platelets_min',
 'h1_potassium_max',
 'h1_potassium_min',
 'h1_sodium_max',
 'h1_sodium_min',
 'h1_wbc_max',
 'h1_wbc_min',
 'd1_arterial_pco2_max',
 'd1_arterial_pco2_min',
 'd1_arterial_ph_max',
 'd1_arterial_ph_min',
 'd1_arterial_po2_max',
 'd1_arterial_po2_min',
 'd1_pao2fio2ratio_max',
 'd1_pao2fio2ratio_min',
 'h1_arterial_pco2_max',
 'h1_arterial_pco2_min',
 'h1_arterial_ph_max',
 'h1_arterial_ph_min',
 'h1_arterial_po2_max',
 'h1_arterial_po2_min',
 'h1_pao2fio2ratio_max',
 'h1_pao2fio2ratio_min']

In [32]:
sample_count = df.shape[0]
sample_count

130157

In [49]:
temp = df[labs_name[0]]
temp = temp.dropna()
np.sqrt(temp.var())

0.6756058360154431

In [51]:
mins = []
maxs = []
means = []
sds = []
na_rates = []
for name in labs_name:
    temp = df[name]
    temp = temp.dropna()
    na_rate = (sample_count - len(temp)) / sample_count
    mins.append(temp.min())
    maxs.append(temp.max())
    means.append(temp.mean())
    sds.append(np.sqrt(temp.var()))
    na_rates.append(na_rate)
    print("column: ", name, " has min: ", temp.min(), ", max: ", temp.max(), ", mean: ", temp.mean(), ", sd: ", np.sqrt(temp.var()), ", na rate: ", na_rate)

column:  d1_albumin_max  has min:  1.2 , max:  4.6 , mean:  2.9526731459890154 , sd:  0.6756058360154431 , na rate:  0.5486143657275444
column:  d1_albumin_min  has min:  1.1 , max:  4.5 , mean:  2.8830734796003648 , sd:  0.679807671446935 , na rate:  0.5486143657275444
column:  d1_bilirubin_max  has min:  0.2 , max:  60.2 , mean:  1.1913793942571382 , sd:  2.319164596941098 , na rate:  0.5895572270411887
column:  d1_bilirubin_min  has min:  0.2 , max:  58.0 , mean:  1.1174046273071956 , sd:  2.2015252104639074 , na rate:  0.5895572270411887
column:  d1_bun_max  has min:  4.0 , max:  126.0 , mean:  25.578808396966235 , sd:  20.495927111483798 , na rate:  0.10551871970005455
column:  d1_bun_min  has min:  3.0 , max:  113.09 , mean:  23.554154161978268 , sd:  18.708332041394122 , na rate:  0.10551871970005455
column:  d1_calcium_max  has min:  6.2 , max:  10.8 , mean:  8.379782311726075 , sd:  0.7400984543927169 , na rate:  0.12824511935585486
column:  d1_calcium_min  has min:  5.5 , max:  10.3 , mean:  8.164673687921471 , sd:  0.793055282271473 , na rate:  0.12824511935585486
column:  d1_creatinine_max  has min:  0.34 , max:  11.11 , mean:  1.4935314243181144 , sd:  1.5259064880190882 , na rate:  0.10197684335072259
column:  d1_creatinine_min  has min:  0.3 , max:  9.9379 , mean:  1.3637950917148551 , sd:  1.3416418075567644 , na rate:  0.10197684335072259
column:  d1_glucose_max  has min:  73.0 , max:  611.0 , mean:  174.14980231966797 , sd:  86.54546561187027 , na rate:  0.0633312076953218
column:  d1_glucose_min  has min:  33.0 , max:  288.0 , mean:  114.44031038272881 , sd:  38.21768211217434 , na rate:  0.0633312076953218
column:  d1_hco3_max  has min:  12.0 , max:  40.0 , mean:  24.452871673780773 , sd:  4.36498994585778 , na rate:  0.1540216815077176
column:  d1_hco3_min  has min:  7.0 , max:  39.0 , mean:  23.192344019616787 , sd:  5.000292761328414 , na rate:  0.1540216815077176
column:  d1_hemaglobin_max  has min:  6.8 , max:  17.2 , mean:  11.459810401579965 , sd:  2.149212586582835 , na rate:  0.12471092603548023
column:  d1_hemaglobin_min  has min:  5.3 , max:  16.7 , mean:  10.90149133201668 , sd:  2.338048121809185 , na rate:  0.12471092603548023
column:  d1_hematocrit_max  has min:  20.4 , max:  51.5 , mean:  34.55583360245721 , sd:  6.1946163279997295 , na rate:  0.11976305538695575
column:  d1_hematocrit_min  has min:  16.1 , max:  50.0 , mean:  32.93929946146022 , sd:  6.80634995641567 , na rate:  0.11976305538695575
column:  d1_inr_max  has min:  0.9 , max:  7.756 , mean:  1.5777884929715191 , sd:  0.9464772196308532 , na rate:  0.62396183071214
column:  d1_inr_min  has min:  0.9 , max:  6.127000000000001 , mean:  1.4634728465183158 , sd:  0.7376387677426538 , na rate:  0.62396183071214
column:  d1_lactate_max  has min:  0.4 , max:  19.8 , mean:  2.9220750851272643 , sd:  3.0574433839712896 , na rate:  0.7337523145124734
column:  d1_lactate_min  has min:  0.4 , max:  15.1 , mean:  2.0781448029087626 , sd:  2.0642908012129704 , na rate:  0.7337523145124734
column:  d1_platelets_max  has min:  27.0 , max:  585.0 , mean:  205.89209677419356 , sd:  89.5474768140511 , na rate:  0.14257396836128675
column:  d1_platelets_min  has min:  18.55 , max:  557.45 , mean:  194.9163552867382 , sd:  88.1217573403319 , na rate:  0.14257396836128675
column:  d1_potassium_max  has min:  2.8 , max:  7.0 , mean:  4.253052860701796 , sd:  0.6669421950916762 , na rate:  0.09639128129873921
column:  d1_potassium_min  has min:  2.4 , max:  5.8 , mean:  3.9292555968404517 , sd:  0.5794594272686844 , na rate:  0.09639128129873921
column:  d1_sodium_max  has min:  123.0 , max:  158.0 , mean:  139.1494477572356 , sd:  4.8277517206621035 , na rate:  0.10195379426385058
column:  d1_sodium_min  has min:  117.0 , max:  153.0 , mean:  137.6922728789344 , sd:  4.92624211162794 , na rate:  0.10195379426385058
column:  d1_wbc_max  has min:  1.2 , max:  46.08 , mean:  12.539672485983722 , sd:  6.7828357756421225 , na rate:  0.13390751169741158
column:  d1_wbc_min  has min:  0.9 , max:  40.898 , mean:  11.298566922148908 , sd:  5.924633236779531 , na rate:  0.13390751169741158
column:  h1_albumin_max  has min:  1.1 , max:  4.7 , mean:  3.0085625896700043 , sd:  0.7381698106703116 , na rate:  0.9143188610677874
column:  h1_albumin_min  has min:  1.1 , max:  4.7 , mean:  3.007254304160679 , sd:  0.738456626426004 , na rate:  0.9143188610677874
column:  h1_bilirubin_max  has min:  0.2 , max:  58.0 , mean:  1.1879788267288125 , sd:  2.3757724980611354 , na rate:  0.9208955338552671
column:  h1_bilirubin_min  has min:  0.2 , max:  58.0 , mean:  1.1871726884226743 , sd:  2.3752234198118423 , na rate:  0.9208955338552671
column:  h1_bun_max  has min:  4.0 , max:  135.0 , mean:  25.631219851392697 , sd:  21.377589338600544 , na rate:  0.8066412102307213
column:  h1_bun_min  has min:  4.0 , max:  135.0 , mean:  25.606373822863276 , sd:  21.360675980195126 , na rate:  0.8066412102307213
column:  h1_calcium_max  has min:  5.6 , max:  11.4 , mean:  8.274174781317107 , sd:  0.8927867183334862 , na rate:  0.8137941101900013
column:  h1_calcium_min  has min:  5.3 , max:  11.315 , mean:  8.265049100511646 , sd:  0.9054886528819466 , na rate:  0.8137941101900013
column:  h1_creatinine_max  has min:  0.33 , max:  11.6042 , mean:  1.5265817443739542 , sd:  1.5727713947406428 , na rate:  0.8050585062655101
column:  h1_creatinine_min  has min:  0.33 , max:  11.571 , mean:  1.5243388247349656 , sd:  1.5700696513212609 , na rate:  0.8050585062655101
column:  h1_glucose_max  has min:  59.0 , max:  695.045 , mean:  167.7026246278408 , sd:  94.033461103669 , na rate:  0.5767880329140961
column:  h1_glucose_min  has min:  42.0 , max:  670.0 , mean:  158.908793842132 , sd:  88.29882683316097 , na rate:  0.5767880329140961
column:  h1_hco3_max  has min:  6.0 , max:  39.0 , mean:  22.544112448447112 , sd:  5.138495032137436 , na rate:  0.8174358659157787
column:  h1_hco3_min  has min:  6.0 , max:  39.0 , mean:  22.486145947310835 , sd:  5.144693383225053 , na rate:  0.8174358659157787
column:  h1_hemaglobin_max  has min:  5.1 , max:  17.4 , mean:  11.204165600906252 , sd:  2.3506328645185013 , na rate:  0.7897385465245819
column:  h1_hemaglobin_min  has min:  5.0 , max:  17.3 , mean:  11.088204772170876 , sd:  2.3812241551265196 , na rate:  0.7897385465245819
column:  h1_hematocrit_max  has min:  16.0 , max:  51.7 , mean:  33.73182971214271 , sd:  6.8049027034018605 , na rate:  0.7910139293314996
column:  h1_hematocrit_min  has min:  15.5 , max:  51.5 , mean:  33.34979596338351 , sd:  6.963974528007935 , na rate:  0.7910139293314996
column:  h1_inr_max  has min:  0.9 , max:  7.756 , mean:  1.5777884929715191 , sd:  0.9464772196308532 , na rate:  0.62396183071214
column:  h1_inr_min  has min:  0.9 , max:  6.127000000000001 , mean:  1.4634728465183158 , sd:  0.7376387677426538 , na rate:  0.62396183071214
column:  h1_lactate_max  has min:  0.4 , max:  18.1 , mean:  3.0281976047904084 , sd:  2.898524183722583 , na rate:  0.9101853914887406
column:  h1_lactate_min  has min:  0.4 , max:  18.0195 , mean:  2.9769820786997316 , sd:  2.854952751436507 , na rate:  0.9101853914887406
column:  h1_platelets_max  has min:  20.0 , max:  585.0 , mean:  193.94305714753563 , sd:  92.48647322535126 , na rate:  0.8123189686301928
column:  h1_platelets_min  has min:  20.0 , max:  585.0 , mean:  193.1235058130015 , sd:  92.69275879360558 , na rate:  0.8123189686301928
column:  h1_potassium_max  has min:  2.5 , max:  7.2 , mean:  4.188984183256075 , sd:  0.7601831552167776 , na rate:  0.774610662507587
column:  h1_potassium_min  has min:  2.5 , max:  7.1 , mean:  4.147027883828773 , sd:  0.7494634945164487 , na rate:  0.774610662507587
column:  h1_sodium_max  has min:  114.0 , max:  157.0 , mean:  138.16720468001125 , sd:  5.711628391135118 , na rate:  0.7819863703066297
column:  h1_sodium_min  has min:  114.0 , max:  157.0 , mean:  137.87981392726246 , sd:  5.658036201146364 , na rate:  0.7819863703066297
column:  h1_wbc_max  has min:  1.1 , max:  44.102 , mean:  13.387873153779369 , sd:  6.933160533324474 , na rate:  0.8142935070722281
column:  h1_wbc_min  has min:  1.0898 , max:  44.102 , mean:  13.336484953042952 , sd:  6.915141754543026 , na rate:  0.8142935070722281
column:  d1_arterial_pco2_max  has min:  18.4 , max:  111.0 , mean:  45.34145111169476 , sd:  14.62377484952825 , na rate:  0.6489163087655677
column:  d1_arterial_pco2_min  has min:  14.9 , max:  85.912 , mean:  38.53558705357145 , sd:  10.996253783161093 , na rate:  0.6489163087655677
column:  d1_arterial_ph_max  has min:  7.05428 , max:  7.62 , mean:  7.387687327894235 , sd:  0.08565115202107526 , na rate:  0.6515746367848061
column:  d1_arterial_ph_min  has min:  6.89 , max:  7.557860000000001 , mean:  7.322903469900884 , sd:  0.11153039702983715 , na rate:  0.6515746367848061
column:  d1_arterial_po2_max  has min:  39.0 , max:  540.865 , mean:  165.0038142241103 , sd:  107.08405816012089 , na rate:  0.6454512627058091
column:  d1_arterial_po2_min  has min:  28.0 , max:  448.892 , mean:  102.95747615229588 , sd:  61.51435667079554 , na rate:  0.6454512627058091
column:  d1_pao2fio2ratio_max  has min:  54.8 , max:  834.805 , mean:  287.6000708176855 , sd:  130.3196204655586 , na rate:  0.717126239848798
column:  d1_pao2fio2ratio_min  has min:  36.0 , max:  604.2277778 , mean:  224.00540299962367 , sd:  119.11967482245313 , na rate:  0.717126239848798
column:  h1_arterial_pco2_max  has min:  15.0 , max:  111.505 , mean:  44.55296607531902 , sd:  14.631358686819596 , na rate:  0.8272009957205528
column:  h1_arterial_pco2_min  has min:  14.997 , max:  107.0 , mean:  43.34108056555947 , sd:  14.052014631871245 , na rate:  0.8272009957205528
column:  h1_arterial_ph_max  has min:  6.93 , max:  7.57 , mean:  7.337283216783214 , sd:  0.10592999348536317 , na rate:  0.8286069900197454
column:  h1_arterial_ph_min  has min:  6.9 , max:  7.563 , mean:  7.327770575578213 , sd:  0.10865772902027057 , na rate:  0.8286069900197454
column:  h1_arterial_po2_max  has min:  34.0 , max:  534.905 , mean:  163.0358345808376 , sd:  112.64674344444838 , na rate:  0.8255030463209816
column:  h1_arterial_po2_min  has min:  31.0 , max:  514.905 , mean:  145.9495365885871 , sd:  100.21193481900298 , na rate:  0.8255030463209816
column:  h1_pao2fio2ratio_max  has min:  42.0 , max:  720.0 , mean:  247.52541863580365 , sd:  131.4401666200997 , na rate:  0.8712324346750463
column:  h1_pao2fio2ratio_min  has min:  38.0 , max:  654.8137931 , mean:  239.61735837250114 , sd:  128.5622112273696 , na rate:  0.8712324346750463

In [56]:
comb_lists = list(zip(labs_name, mins, maxs, means, sds, na_rates))
comb_lists

[('d1_albumin_max',
  1.2,
  4.6,
  2.9526731459890154,
  0.6756058360154431,
  0.5486143657275444),
 ('d1_albumin_min',
  1.1,
  4.5,
  2.8830734796003648,
  0.679807671446935,
  0.5486143657275444),
 ('d1_bilirubin_max',
  0.2,
  60.2,
  1.1913793942571382,
  2.319164596941098,
  0.5895572270411887),
 ('d1_bilirubin_min',
  0.2,
  58.0,
  1.1174046273071956,
  2.2015252104639074,
  0.5895572270411887),
 ('d1_bun_max',
  4.0,
  126.0,
  25.578808396966235,
  20.495927111483798,
  0.10551871970005455),
 ('d1_bun_min',
  3.0,
  113.09,
  23.554154161978268,
  18.708332041394122,
  0.10551871970005455),
 ('d1_calcium_max',
  6.2,
  10.8,
  8.379782311726075,
  0.7400984543927169,
  0.12824511935585486),
 ('d1_calcium_min',
  5.5,
  10.3,
  8.164673687921471,
  0.793055282271473,
  0.12824511935585486),
 ('d1_creatinine_max',
  0.34,
  11.11,
  1.4935314243181144,
  1.5259064880190882,
  0.10197684335072259),
 ('d1_creatinine_min',
  0.3,
  9.9379,
  1.3637950917148551,
  1.3416418075567644,
  0.10197684335072259),
 ('d1_glucose_max',
  73.0,
  611.0,
  174.14980231966797,
  86.54546561187027,
  0.0633312076953218),
 ('d1_glucose_min',
  33.0,
  288.0,
  114.44031038272881,
  38.21768211217434,
  0.0633312076953218),
 ('d1_hco3_max',
  12.0,
  40.0,
  24.452871673780773,
  4.36498994585778,
  0.1540216815077176),
 ('d1_hco3_min',
  7.0,
  39.0,
  23.192344019616787,
  5.000292761328414,
  0.1540216815077176),
 ('d1_hemaglobin_max',
  6.8,
  17.2,
  11.459810401579965,
  2.149212586582835,
  0.12471092603548023),
 ('d1_hemaglobin_min',
  5.3,
  16.7,
  10.90149133201668,
  2.338048121809185,
  0.12471092603548023),
 ('d1_hematocrit_max',
  20.4,
  51.5,
  34.55583360245721,
  6.1946163279997295,
  0.11976305538695575),
 ('d1_hematocrit_min',
  16.1,
  50.0,
  32.93929946146022,
  6.80634995641567,
  0.11976305538695575),
 ('d1_inr_max',
  0.9,
  7.756,
  1.5777884929715191,
  0.9464772196308532,
  0.62396183071214),
 ('d1_inr_min',
  0.9,
  6.127000000000001,
  1.4634728465183158,
  0.7376387677426538,
  0.62396183071214),
 ('d1_lactate_max',
  0.4,
  19.8,
  2.9220750851272643,
  3.0574433839712896,
  0.7337523145124734),
 ('d1_lactate_min',
  0.4,
  15.1,
  2.0781448029087626,
  2.0642908012129704,
  0.7337523145124734),
 ('d1_platelets_max',
  27.0,
  585.0,
  205.89209677419356,
  89.5474768140511,
  0.14257396836128675),
 ('d1_platelets_min',
  18.55,
  557.45,
  194.9163552867382,
  88.1217573403319,
  0.14257396836128675),
 ('d1_potassium_max',
  2.8,
  7.0,
  4.253052860701796,
  0.6669421950916762,
  0.09639128129873921),
 ('d1_potassium_min',
  2.4,
  5.8,
  3.9292555968404517,
  0.5794594272686844,
  0.09639128129873921),
 ('d1_sodium_max',
  123.0,
  158.0,
  139.1494477572356,
  4.8277517206621035,
  0.10195379426385058),
 ('d1_sodium_min',
  117.0,
  153.0,
  137.6922728789344,
  4.92624211162794,
  0.10195379426385058),
 ('d1_wbc_max',
  1.2,
  46.08,
  12.539672485983722,
  6.7828357756421225,
  0.13390751169741158),
 ('d1_wbc_min',
  0.9,
  40.898,
  11.298566922148908,
  5.924633236779531,
  0.13390751169741158),
 ('h1_albumin_max',
  1.1,
  4.7,
  3.0085625896700043,
  0.7381698106703116,
  0.9143188610677874),
 ('h1_albumin_min',
  1.1,
  4.7,
  3.007254304160679,
  0.738456626426004,
  0.9143188610677874),
 ('h1_bilirubin_max',
  0.2,
  58.0,
  1.1879788267288125,
  2.3757724980611354,
  0.9208955338552671),
 ('h1_bilirubin_min',
  0.2,
  58.0,
  1.1871726884226743,
  2.3752234198118423,
  0.9208955338552671),
 ('h1_bun_max',
  4.0,
  135.0,
  25.631219851392697,
  21.377589338600544,
  0.8066412102307213),
 ('h1_bun_min',
  4.0,
  135.0,
  25.606373822863276,
  21.360675980195126,
  0.8066412102307213),
 ('h1_calcium_max',
  5.6,
  11.4,
  8.274174781317107,
  0.8927867183334862,
  0.8137941101900013),
 ('h1_calcium_min',
  5.3,
  11.315,
  8.265049100511646,
  0.9054886528819466,
  0.8137941101900013),
 ('h1_creatinine_max',
  0.33,
  11.6042,
  1.5265817443739542,
  1.5727713947406428,
  0.8050585062655101),
 ('h1_creatinine_min',
  0.33,
  11.571,
  1.5243388247349656,
  1.5700696513212609,
  0.8050585062655101),
 ('h1_glucose_max',
  59.0,
  695.045,
  167.7026246278408,
  94.033461103669,
  0.5767880329140961),
 ('h1_glucose_min',
  42.0,
  670.0,
  158.908793842132,
  88.29882683316097,
  0.5767880329140961),
 ('h1_hco3_max',
  6.0,
  39.0,
  22.544112448447112,
  5.138495032137436,
  0.8174358659157787),
 ('h1_hco3_min',
  6.0,
  39.0,
  22.486145947310835,
  5.144693383225053,
  0.8174358659157787),
 ('h1_hemaglobin_max',
  5.1,
  17.4,
  11.204165600906252,
  2.3506328645185013,
  0.7897385465245819),
 ('h1_hemaglobin_min',
  5.0,
  17.3,
  11.088204772170876,
  2.3812241551265196,
  0.7897385465245819),
 ('h1_hematocrit_max',
  16.0,
  51.7,
  33.73182971214271,
  6.8049027034018605,
  0.7910139293314996),
 ('h1_hematocrit_min',
  15.5,
  51.5,
  33.34979596338351,
  6.963974528007935,
  0.7910139293314996),
 ('h1_inr_max',
  0.9,
  7.756,
  1.5777884929715191,
  0.9464772196308532,
  0.62396183071214),
 ('h1_inr_min',
  0.9,
  6.127000000000001,
  1.4634728465183158,
  0.7376387677426538,
  0.62396183071214),
 ('h1_lactate_max',
  0.4,
  18.1,
  3.0281976047904084,
  2.898524183722583,
  0.9101853914887406),
 ('h1_lactate_min',
  0.4,
  18.0195,
  2.9769820786997316,
  2.854952751436507,
  0.9101853914887406),
 ('h1_platelets_max',
  20.0,
  585.0,
  193.94305714753563,
  92.48647322535126,
  0.8123189686301928),
 ('h1_platelets_min',
  20.0,
  585.0,
  193.1235058130015,
  92.69275879360558,
  0.8123189686301928),
 ('h1_potassium_max',
  2.5,
  7.2,
  4.188984183256075,
  0.7601831552167776,
  0.774610662507587),
 ('h1_potassium_min',
  2.5,
  7.1,
  4.147027883828773,
  0.7494634945164487,
  0.774610662507587),
 ('h1_sodium_max',
  114.0,
  157.0,
  138.16720468001125,
  5.711628391135118,
  0.7819863703066297),
 ('h1_sodium_min',
  114.0,
  157.0,
  137.87981392726246,
  5.658036201146364,
  0.7819863703066297),
 ('h1_wbc_max',
  1.1,
  44.102,
  13.387873153779369,
  6.933160533324474,
  0.8142935070722281),
 ('h1_wbc_min',
  1.0898,
  44.102,
  13.336484953042952,
  6.915141754543026,
  0.8142935070722281),
 ('d1_arterial_pco2_max',
  18.4,
  111.0,
  45.34145111169476,
  14.62377484952825,
  0.6489163087655677),
 ('d1_arterial_pco2_min',
  14.9,
  85.912,
  38.53558705357145,
  10.996253783161093,
  0.6489163087655677),
 ('d1_arterial_ph_max',
  7.05428,
  7.62,
  7.387687327894235,
  0.08565115202107526,
  0.6515746367848061),
 ('d1_arterial_ph_min',
  6.89,
  7.557860000000001,
  7.322903469900884,
  0.11153039702983715,
  0.6515746367848061),
 ('d1_arterial_po2_max',
  39.0,
  540.865,
  165.0038142241103,
  107.08405816012089,
  0.6454512627058091),
 ('d1_arterial_po2_min',
  28.0,
  448.892,
  102.95747615229588,
  61.51435667079554,
  0.6454512627058091),
 ('d1_pao2fio2ratio_max',
  54.8,
  834.805,
  287.6000708176855,
  130.3196204655586,
  0.717126239848798),
 ('d1_pao2fio2ratio_min',
  36.0,
  604.2277778,
  224.00540299962367,
  119.11967482245313,
  0.717126239848798),
 ('h1_arterial_pco2_max',
  15.0,
  111.505,
  44.55296607531902,
  14.631358686819596,
  0.8272009957205528),
 ('h1_arterial_pco2_min',
  14.997,
  107.0,
  43.34108056555947,
  14.052014631871245,
  0.8272009957205528),
 ('h1_arterial_ph_max',
  6.93,
  7.57,
  7.337283216783214,
  0.10592999348536317,
  0.8286069900197454),
 ('h1_arterial_ph_min',
  6.9,
  7.563,
  7.327770575578213,
  0.10865772902027057,
  0.8286069900197454),
 ('h1_arterial_po2_max',
  34.0,
  534.905,
  163.0358345808376,
  112.64674344444838,
  0.8255030463209816),
 ('h1_arterial_po2_min',
  31.0,
  514.905,
  145.9495365885871,
  100.21193481900298,
  0.8255030463209816),
 ('h1_pao2fio2ratio_max',
  42.0,
  720.0,
  247.52541863580365,
  131.4401666200997,
  0.8712324346750463),
 ('h1_pao2fio2ratio_min',
  38.0,
  654.8137931,
  239.61735837250114,
  128.5622112273696,
  0.8712324346750463)]

In [57]:
temp_df = pd.DataFrame(comb_lists, columns = ["variable", "min", "max", "mean", "sd", "na_rate"])
temp_df

                variable   min         max        mean          sd   na_rate
0         d1_albumin_max   1.2    4.600000    2.952673    0.675606  0.548614
1         d1_albumin_min   1.1    4.500000    2.883073    0.679808  0.548614
2       d1_bilirubin_max   0.2   60.200000    1.191379    2.319165  0.589557
3       d1_bilirubin_min   0.2   58.000000    1.117405    2.201525  0.589557
4             d1_bun_max   4.0  126.000000   25.578808   20.495927  0.105519
..                   ...   ...         ...         ...         ...       ...
71    h1_arterial_ph_min   6.9    7.563000    7.327771    0.108658  0.828607
72   h1_arterial_po2_max  34.0  534.905000  163.035835  112.646743  0.825503
73   h1_arterial_po2_min  31.0  514.905000  145.949537  100.211935  0.825503
74  h1_pao2fio2ratio_max  42.0  720.000000  247.525419  131.440167  0.871232
75  h1_pao2fio2ratio_min  38.0  654.813793  239.617358  128.562211  0.871232

[76 rows x 6 columns]

In [58]:
temp_df.to_excel("stats.xlsx")

In [34]:
# print(df.isna().sum().sort_values(ascending=False).to_string())

In [4]:
df = df.dropna(0)

In [5]:
df.shape

(63, 181)

In [6]:
cat_names = df.columns.to_series().groupby(df.dtypes).groups.get(np.dtype('O')).tolist()
cat_names

['ethnicity',
 'gender',
 'hospital_admit_source',
 'icu_admit_source',
 'icu_stay_type',
 'icu_type']

In [7]:
df_copy = df

In [8]:
for i in range(len(cat_names)):
    # Code below adapted from:
    # https://stackoverflow.com/questions/23208745/adding-dummy-columns-to-the-original-dataframe
    df_copy = pd.concat([df_copy, pd.get_dummies(df_copy[cat_names[i]])], axis=1)
    df_copy = df_copy.drop(columns=[cat_names[i]])

In [9]:
df_copy

,Unnamed: 0,encounter_id,hospital_id,age,bmi,elective_surgery,height,icu_id,pre_icu_los_days,readmission_status,...,Floor,Operating Room / Recovery,Other Hospital,admit,CCU-CTICU,CSICU,Cardiac ICU,MICU,Med-Surg ICU,SICU
8230,8231,232100,89,67.0,28.146291,0,167.64,133,0.000000,0,...,0,0,0,1,0,0,0,0,1,0
8435,8436,275481,89,60.0,34.574559,0,177.80,133,0.047222,0,...,0,0,0,1,0,0,0,0,1,0
8657,8658,278577,89,66.0,25.775925,1,185.40,133,1.147222,0,...,0,1,0,1,0,0,0,0,1,0
8667,8668,278295,89,55.0,56.659238,0,162.60,133,0.127778,0,...,0,1,0,1,0,0,0,0,1,0
9170,9171,236541,89,21.0,22.180764,0,182.90,133,0.000000,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126019,126020,226636,163,28.0,20.899654,1,170.00,1078,5.543750,0,...,0,1,0,1,0,0,0,0,1,0
126142,126143,276831,163,40.0,29.579512,0,171.50,1078,0.015972,0,...,0,0,0,1,0,0,0,0,1,0
126682,126683,223598,163,60.0,39.525303,0,162.60,1078,0.005556,0,...,0,0,1,1,0,0,0,0,1,0
126847,126848,255666,7,60.0,28.541194,0,157.50,1109,0.000000,0,...,0,0,0,1,0,0,1,0,0,0
126857,126858,230960,7,28.0,28.652128,0,165.10,1109,0.000000,0,...,0,0,1,1,0,0,1,0,0,0

SyntaxError: invalid syntax (<ipython-input-10-e8a115376182>, line 1)